### ISSUE TITLE
Report Map clarification 

### ISSUE THREAD

**Issue by lewisjustin749** [NateXVI/ESP32-HID-Gamepad#2]
More of a question rather than an issue. In your current code for the gamepad, is it possible to make changes on the report map without having to change other variables to deal with memory. I am working on a gamepad with 2 buttons and 1 joystick, but my program has trouble connecting to the computer when I make changes to the report map.

**Comment by NateXVI** [comment]
Yes you can make changes to the repot map, but changing the report map also changes the report size. It's been years since I've done anything with report maps, but I'm pretty sure it's best to have a multiple of 8 buttons even if you only use two of them. That way the button section of the report can be x number of bytes long. Report maps can be pretty tricky and are what I spent the most time on while making this program.

I recommend checking out this library that will make things easier for you: [ESP32-BLE-Gamepad](https://github.com/lemmingDev/ESP32-BLE-Gamepad)
